#!/usr/bin/env bash
# WealthOS Deploy Script — generated by Cowork session 2026-05-27
# Run from: /Users/user/Documents/Claude/Projects/WealthOS/
# Usage: bash deploy.sh
set -e

REPO="/Users/user/Documents/Claude/Projects/WealthOS"
SERVER="root@64.227.147.106"
REMOTE_BACKEND="/opt/wlthos/backend"
REMOTE_FRONTEND="/var/www/wlthos"

cd "$REPO"

echo "═══════════════════════════════════════════"
echo "  WealthOS Deploy — $(date '+%Y-%m-%d %H:%M')"
echo "═══════════════════════════════════════════"

# ── 1. Git commit all changes ───────────────────
echo ""
echo "▶ [1/4] Committing changes to git..."
git add -f frontend/dist/dashboard.html frontend/dist/index.html frontend/dist/app.html 2>/dev/null || true
git add backend/app/api/v1/demo.py backend/main.py 2>/dev/null || true
git add -A 2>/dev/null || true

CHANGED=$(git diff --cached --name-only 2>/dev/null | wc -l | tr -d ' ')
if [ "$CHANGED" -gt "0" ]; then
  git commit -m "phase 1-3+6: landing real API, auth register, dashboard real data, demo backend — $(date '+%Y-%m-%d')" 2>/dev/null || true
  echo "   ✓ Committed $CHANGED files"
else
  echo "   ✓ Nothing new to commit (already up to date)"
fi

# ── 2. Deploy backend ───────────────────────────
echo ""
echo "▶ [2/4] Deploying backend to server..."
rsync -avz --delete \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  --exclude '*.db' \
  --exclude '*.sqlite*' \
  --exclude '.env' \
  --exclude 'venv/' \
  --exclude '.venv/' \
  "$REPO/backend/" \
  "$SERVER:$REMOTE_BACKEND/"
echo "   ✓ Backend synced"

# ── 3. Deploy frontend ──────────────────────────
echo ""
echo "▶ [3/4] Deploying frontend to server..."
rsync -avz --delete \
  "$REPO/frontend/dist/" \
  "$SERVER:$REMOTE_FRONTEND/"

# Fix HTML permissions (Nginx needs 644)
ssh "$SERVER" "chmod 644 $REMOTE_FRONTEND/*.html 2>/dev/null || true"
echo "   ✓ Frontend synced"

# ── 4. Restart backend service ──────────────────
echo ""
echo "▶ [4/4] Restarting wealthos service..."
ssh "$SERVER" "systemctl restart wealthos && sleep 2 && systemctl is-active wealthos"
echo "   ✓ Service restarted"

# ── Health check ────────────────────────────────
echo ""
echo "▶ Health check..."
HEALTH=$(curl -sf https://api.wlthos.in/health 2>/dev/null || echo "FAILED")
echo "   API: $HEALTH"

SITE=$(curl -sf -o /dev/null -w "%{http_code}" https://wlthos.in 2>/dev/null || echo "000")
echo "   Site: HTTP $SITE"

echo ""
echo "═══════════════════════════════════════════"
if echo "$HEALTH" | grep -q '"status":"ok"'; then
  echo "  ✅  DEPLOY COMPLETE — wlthos.in is live"
else
  echo "  ⚠   Deploy done but health check uncertain"
  echo "  Manual check: curl https://api.wlthos.in/health"
fi
echo "═══════════════════════════════════════════"
